version: "3"

vars:
  MODNAME:
    sh: go list -m
  APPNAME: "{{.MODNAME | base}}"
  VERSION:
    sh: git describe --tags --always
  REVISION:
    sh: git rev-parse --short HEAD
  DATE:
    sh: date "+%F"
  LDFLAGS: >-
    -w
    -s
    -X main.Version={{.VERSION}}
    -X main.DateBuilt={{.DATE}}
  GOFLAGS: >-
    -trimpath
  DOCKER_IMAGE: "{{.MODNAME}}"
  DOCKER_TAG: "{{.VERSION}}"

tasks:
  go:update:
    cmds:
      - go get -u ./...

  go:tidy:
    cmds:
      - go mod tidy

  go:lint:
    sources:
      - "**/*.go"
    cmds:
      - golangci-lint run --verbose

  go:fmt:
    sources:
      - "**/*.go"
    cmds:
      - gofumpt -w -l .

  go:test:
    sources:
      - "**/*_test.go"
    cmds:
      - go test ./...

  go:build:
    sources:
      - "**/*.go"
    deps:
      - go:tidy
    cmds:
      - go build {{.GOFLAGS}} -ldflags "{{.LDFLAGS}}" -o {{.APPNAME}} ./cmd/redpanda-connect

  go:release:
    cmds:
      - goreleaser release --snapshot --clean

  docker:build:
    cmds:
      - docker build --tag {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} --tag {{.DOCKER_IMAGE}}:latest .
