logger:
  level: debug

input:
  yandex_metrika_goals:
    token: ${YANDEX_METRIKA_TOKEN:""}
    counter_id: 44147844

pipeline:
  processors:
    - mutation: |
        #!blobl
        root.fetched_at = now()

output:
  stdout: {}
